# 开发环境配置
springdoc:
  paths-to-match: /api/**
  swagger-ui:
    operations-sorter: alpha
spring:
  influxdb:
    url: http://129.204.155.72:8086
    user: root
    password: xznxznxzn
  mail:
    password: BEAGDULMBXDYOGGO
    username: zhennan996@163.com
    host: smtp.163.com
    port: 465
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
  rabbitmq:
    host: 129.204.155.72
    username: xzn
    password: Nruonan996
    virtual-host: /
    port: 5672
  data:
    redis:
      port: 6379
      password: Nruonan996
      host: 129.204.155.72
  security:
    jwt:
      expire: 24
      key: xznzzhxzn
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 50
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://129.204.155.72:3306/test?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: zzh2002
server:
  port: 8081
